language: pyton
pyton:
 -"2.7"

branches:
 only:
  - gh-pages
  
  # install Java 8 as required by vnu.jar
  before_install:
   - sudo apt-get update
   - sudo apt-get install oracle-java8-installer
   - sudo update-java-alternatives -s java-8-oracle-java8-installer
  
install:
    - pip install html5validator
	
script: html5validator --root.